SCENARIOS = [
    {
        "id": "normale",
        "score": 12,
        "carrier": "Maersk",
        "route": "Shanghai → Rotterdam → Le Havre",
        "period": "Q1 2026",
        "anomalies_count": 1,
        "lines": [
            {
                "code": "Ocean Freight",
                "desc": "Fret de base – conteneur 40' HC",
                "amount": "2 100 USD",
                "status": "ok",
                "verdict": "✓ Dans la fourchette FBX Q1 2026",
            },
            {
                "code": "BAF Q1 2026",
                "desc": "Surcharge carburant – VLSFO référence jan.",
                "amount": "290 USD",
                "status": "ok",
                "verdict": "✓ Conforme formule Maersk",
            },
            {
                "code": "CAF",
                "desc": "Currency Adjustment Factor – risque change USD/EUR",
                "amount": "38 USD",
                "status": "ok",
                "verdict": "✓ Conforme",
            },
            {
                "code": "THC Rotterdam",
                "desc": "Manutention portuaire – terminal ECT Delta",
                "amount": "185 EUR",
                "status": "ok",
                "verdict": "✓ Tarif standard Rotterdam",
            },
            {
                "code": "Frais documentaires",
                "desc": "Connaissement + frais de télex release",
                "amount": "225 EUR",
                "status": "warn",
                "verdict": "⚠ +18% vs tarif standard — Écart : ~35 EUR",
            },
        ],
        "summary": "1 anomalie détectée. Les frais documentaires sont facturés 18% au-dessus du tarif standard pour ce port. Montant contestable : ~35 EUR.",
        "summary_type": "warn",
        "recoverable": "35 EUR",
    },
    {
        "id": "baf_eleve",
        "score": 34,
        "carrier": "CMA CGM",
        "route": "Shanghai → Le Havre",
        "period": "Q1 2026",
        "anomalies_count": 2,
        "lines": [
            {
                "code": "Ocean Freight",
                "desc": "Fret de base – transport conteneur 20'",
                "amount": "1 850 USD",
                "status": "ok",
                "verdict": "✓ Dans la norme marché",
            },
            {
                "code": "BAF Q1 2026",
                "desc": "Surcharge carburant – indexée fuel lourd VLSFO",
                "amount": "312 USD",
                "status": "warn",
                "verdict": "⚠ +22% vs référence Q1 — Écart : ~56 USD",
            },
            {
                "code": "Green Levy (ETS)",
                "desc": "Surcharge EU ETS – marché carbone européen",
                "amount": "127 USD",
                "status": "err",
                "verdict": "✕ +41% vs calcul EUA théorique — Écart : ~52 USD",
            },
            {
                "code": "PSS",
                "desc": "Peak Season Surcharge – haute saison",
                "amount": "85 USD",
                "status": "err",
                "verdict": "✕ Non applicable hors saison (oct–janv)",
            },
            {
                "code": "CAF",
                "desc": "Currency Adjustment Factor – risque change",
                "amount": "43 USD",
                "status": "ok",
                "verdict": "✓ Conforme",
            },
            {
                "code": "THC Le Havre",
                "desc": "Manutention portuaire – terminal Port 2000",
                "amount": "210 EUR",
                "status": "ok",
                "verdict": "✓ Tarif standard",
            },
            {
                "code": "Frais documentaires",
                "desc": "Connaissement + documents douaniers",
                "amount": "185 EUR",
                "status": "ok",
                "verdict": "✓ Conforme",
            },
        ],
        "summary": "2 anomalies détectées. La surcharge ETS est facturée 41% au-dessus du calcul théorique basé sur le prix des EUA à la date du B/L. La PSS est inapplicable hors période haute saison. Montant potentiellement récupérable : ~185 USD.",
        "summary_type": "err",
        "recoverable": "185 USD",
    },
    {
        "id": "surestaries",
        "score": 28,
        "carrier": "MSC",
        "route": "Ningbo → Marseille",
        "period": "Févr. 2026",
        "anomalies_count": 1,
        "lines": [
            {
                "code": "Ocean Freight",
                "desc": "Fret de base – conteneur 40' standard",
                "amount": "1 620 USD",
                "status": "ok",
                "verdict": "✓ Dans la fourchette FBX",
            },
            {
                "code": "LSS / BAF",
                "desc": "Low Sulphur Surcharge – carburant faible soufre",
                "amount": "245 USD",
                "status": "ok",
                "verdict": "✓ Conforme formule MSC",
            },
            {
                "code": "ECA Surcharge",
                "desc": "Emission Control Area – zone SECA Méditerranée",
                "amount": "78 USD",
                "status": "ok",
                "verdict": "✓ Applicable en zone ECA",
            },
            {
                "code": "THC Marseille",
                "desc": "Manutention – terminal Fos-sur-Mer",
                "amount": "195 EUR",
                "status": "ok",
                "verdict": "✓ Tarif standard Fos",
            },
            {
                "code": "D&D Surestaries",
                "desc": "Demurrage 8 jours × 75$/j – dépassement jours francs",
                "amount": "600 USD",
                "status": "err",
                "verdict": "✕ 3 jours non ouvrés non déduits — Récupérable : ~225 USD",
            },
            {
                "code": "Frais documentaires",
                "desc": "B/L + Telex release",
                "amount": "170 EUR",
                "status": "ok",
                "verdict": "✓ Conforme",
            },
        ],
        "summary": "1 anomalie détectée. Les surestaries incluent 3 jours non ouvrés (week-end + jour férié) qui auraient dû être déduits selon la règlementation FMC 2024. Montant contestable : 225 USD sur 600 USD facturés.",
        "summary_type": "err",
        "recoverable": "225 USD",
    },
    {
        "id": "multi_anomalies",
        "score": 52,
        "carrier": "Hapag-Lloyd",
        "route": "Busan → Hambourg → Le Havre",
        "period": "Mars 2026",
        "anomalies_count": 3,
        "lines": [
            {
                "code": "Ocean Freight",
                "desc": "Fret de base – conteneur 40' HC",
                "amount": "2 850 USD",
                "status": "warn",
                "verdict": "⚠ +17% vs FBX Q1 2026 — Au-dessus de la fourchette haute",
            },
            {
                "code": "BAF Mars 2026",
                "desc": "Surcharge carburant – VLSFO Rotterdam",
                "amount": "510 USD",
                "status": "err",
                "verdict": "✕ +55% vs formule Hapag-Lloyd publiée — Écart : ~183 USD",
            },
            {
                "code": "PSS",
                "desc": "Peak Season Surcharge",
                "amount": "120 USD",
                "status": "err",
                "verdict": "✕ Non applicable en mars (hors période oct–janv)",
            },
            {
                "code": "ETS / Green Levy",
                "desc": "Surcharge marché carbone EU",
                "amount": "198 USD",
                "status": "err",
                "verdict": "✕ +38% vs calcul EUA à la date du B/L — Écart : ~73 USD",
            },
            {
                "code": "CAF",
                "desc": "Currency Adjustment Factor",
                "amount": "55 USD",
                "status": "ok",
                "verdict": "✓ Conforme",
            },
            {
                "code": "THC Le Havre",
                "desc": "Manutention – terminal Port 2000",
                "amount": "210 EUR",
                "status": "ok",
                "verdict": "✓ Tarif standard",
            },
            {
                "code": "Frais documentaires",
                "desc": "B/L + Surrender fee",
                "amount": "215 EUR",
                "status": "ok",
                "verdict": "✓ Conforme",
            },
        ],
        "summary": "3 anomalies détectées. Le BAF est facturé 55% au-dessus de la formule officielle Hapag-Lloyd. La PSS est inapplicable en mars. L'ETS est surévalué de 38% par rapport au prix EUA à la date du connaissement. Montant potentiellement récupérable : ~376 USD.",
        "summary_type": "err",
        "recoverable": "376 USD",
    },
]
